### PR TITLE
Sort events on same date by start time

### PR DESCRIPTION
**Pull request by mattlub**
#91

### CODE REVIEW

**Comment by HilbertSpitzer** [comment]
"converts events from array of event objs into array of objects of form { date, events array }"
...
I don't get it

**Comment by mattlub** [comment]
@HilbertSpitzer if you have a comment about a specific line, please comment on that specific line by going to the 'files changed' bit- if you can't work it out, ask someone

**Comment by mattlub** [comment]
"converts events from array of event objs into array of objects of form { date, events array }"

The function input is an array of event objects
The output is an array of objects, each of the form 
```js
{
   date: <date>,
   events: [
      <event object>,
      <event object>,
   ]
}
```

**Comment by HilbertSpitzer** [comment]
```"<event object>" ```
= array of event objects? = all of the details about the event
"events: [ ...... ]" = array of form objects? = array of the above ordered in a form with a design of its own
?

**Comment by mattlub** [comment]
sorry I don't fully understand your question but an 'event object' is
```js
{
  title: 'title of event',
  start_time: '10:00:00',
  location: 'liwan',
  date: '2017-10-10',
  etc.
}
```

**Comment by HilbertSpitzer** [comment]
Which is contained in  event object  between <> right?

And an " array of objects of form" is an array of event objects right? Or what, is it just a plain container?

Basically I don't understand the wording

**Comment by mattlub** [comment]
Ah ok I see the problem, when I say 'form' I mean structure or format.

So  "an array of objects with the structure..."

**Comment by HilbertSpitzer** [comment]
Right. And "an array of objects of form { **date**, events array }" is the collection of all of them that are associated with the thing that shows up first thing inside the curly brackets, which in this case happens to be the **date**
Did I get that right?
Is that even a real tech term or did you write this in a hurry?

**Comment by mattlub** [comment]
Yes I think you have it more or less right. Does this clear it up??

The output is an array of objects, each object in the array has the following structure:
```js
{
   date: <date>,
   events: <array of events on this date>
}
```

> Is that even a real tech term or did you write this in a hurry?

Are you referring to the word "form"? It is not a tech word, it just means structure

**Comment by HilbertSpitzer** [comment]
The term "array of objects of form { date, events array }", that term just wasn't clear to me and I don't think it's an actual term, is what I'm saying

**Review by HilbertSpitzer — APPROVED** [review]

**Comment by mattlub** [comment]
I don't know what you mean by an "actual term", what I wrote was correct, only skipping the word "the" for brevity, is this clearer for you?

"array of objects of **the** form { date, events array }"

**Comment by HilbertSpitzer** [comment]
I already approved this

**Pull request merged**
