### PR TITLE
clean up the header

### PR DESCRIPTION
**Pull request by mattlub**
cleans up the header.

also adds back button when headerHasBackButton: true is passed to the hbs template

does the above for the event detail page

#97

### CODE REVIEW

**Comment by HilbertSpitzer** [comment]
Does it have a next button? what's up with the last few lines of code?

**Comment by mattlub** [comment]
there is no next button. I added the possibility for a back button, e.g. for on the event detail page, to take you back to the list view.

which lines are you referring to? comment on the specific lines?

**Comment by mattlub** [comment]
@HilbertSpitzer I just made another commit, and updated the PR description

**Comment by HilbertSpitzer** [comment]
Can you explain headerHasCalendarButton?

**Comment by mattlub** [comment]
headerHasCalendarButton is a boolean which is passed to a template, indicating whether the header should have the calendar button (icon).

e.g. the home page has headerHasCalendarButton =  true

**Comment by HilbertSpitzer** [comment]
And when should it have the calendar button and when it shouldn't? Depending on whether the user previously clicked? What are we talking about here?

**Comment by mattlub** [comment]
the header should have the calendar button when it is on the home page, but not when it is on the event detail page.

**Comment by HilbertSpitzer** [comment]
Why restrict this only to the homepage?

**Comment by mattlub** [comment]
no particular reason. we definitely could have it on other pages, but may take time to implement

**Review by HilbertSpitzer — APPROVED** [review]

**Pull request merged**
